#!/usr/bin/perl
#Version 0.0003
# This program was auto generated by PerlQTRAD
#Copyright 1998 Simon Loader
#  If you need to edit this file (which you probably
# will) then the program is not fulling your needs

package gui;

# this is a use list
use Qt;
use QWidget;
use QPushButton;
use QLabel;
use QToolTip;
use QSlider;

#Slots to use / connections
use slots qw{helloproc() };


@ISA = qw{QWidget};

sub new {
	my $class = shift;
	my $self = $class->SUPER::new();

	$self->setMinimumSize(200,200);
	$self->setMaximumSize(200,200);
	my $RAD0 = new QPushButton($self)->immortal;
	$RAD0->setGeometry(28,27,88,42)
;
	$RAD0->setText("hello");
	$RAD0->setCursor(new QCursor(2));
	$self->connect($RAD0,'pressed()','helloproc()');
	QToolTip::add($RAD0,'This prints hello');



	if ($self->can('init'))
		{
		$self->init();
		}
	bless ($self,$class);
	return $self;
}





sub helloproc
	{
	print "hello\n";
	}



package main;
use Qt;

$mygui = new gui;
$qApp->setMainWidget($mygui);
$mygui->show();
exit $qApp->exec();
